{% set version = "2.3-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-evd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/evd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/evd/evd_{{ version }}.tar.gz
  sha256: 4a899df15d39be4a8d544de4f5e4690b4673790a46da6a6c9c2a70fef3b55648

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('evd')"           # [not win]
    - "\"%R%\" -e \"library('evd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=evd
  license: GPL-3.0-only
  summary: Extends simulation, distribution, quantile and density functions to univariate and multivariate parametric extreme value distributions, and provides fitting functions which calculate maximum likelihood estimates for univariate and bivariate maxima models, and for univariate and bivariate threshold models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - daf
