appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LBRcXSiFw3qG4bDxkDYvgMB+Awfo4TJFRZeosELrHXGCqUrxjIgJQAki0RYhfirq1eHl1N+qVALymegdssO5CVLQkcR8ETIgukdhtn0tc/tDNmqF7XTay8aFUxPCi/jDMSEjzxgOhiJduuRdGZ18ou2Z2FvEIEuPl67/v4WuEhATxM9UKVKK+cPy1QdV7oNeG4bq8pZPGYrHttSwh1i+BssbNxIcaQj86Uqua+Eaa76313tsakr+NKqGYCWl1fm1EgFi4DnPXrz7t7Jr2+KZOCphDvMJlJRadId30o0a/zJBxJbhTkf8Ro9nvDzV4R5765S4NwUY87z3WRyBgxIxD8yWhsFVwF5RO6ibuaryxI6pzXjuyV7jOKs00j1dGhopOM4doSk/IkziETGUn2fdDqp8ZsSP842BxxJvm29JE8P/smQX49HiHTezpkMJ86z3n5kNUQh3ZkfDRI/Hb9tsEmcWcvG0PC6Lc1O3OHkKpthfF+ccAMrFg7PR5kYDvlfk0FXJRahSXCXYmOzx/ixR8GSbMPyJU1mRW0asET+pjIWdg/9rTnJ87YWcD4OOiYN0PE5gCnAIHC97NGTJ9noM0s3G9AUH4eviVG3tI0mzWWJwNTWlmwHLmghOvnHvB9Solxtj5RD4cgGk6icMf0gjKLtGnbPbEzlM8fspVROtOrQ=
