travis:
  secure:
    BINSTAR_TOKEN: e5CJs3vV0rkdQuCKZnRYQJLidYojfHrBptxAK7O6MSrERXKow9iOSNl25Do8dDm3SmfK0InyyLzzSR1fF/EXBc6if6nO9u3k07Jt5FW0sD7lfSaWFamVy9tZZmyi2PBL/whZRLcjtOJhHWGsgnLTewCN+4vnqryhiyYMBbEf8pt/NZjW0q7/rW0nf7AKYouz2/XqQmdKumeiS09+3sjos4sFjqDJmfJfy+VHf6XPivnLZfq+FTav4aei3kIY4wZWh1QD795RXlNtV9+/td/iDJyP7HugBuLRAElSCO3/jOmn7zfXA7QR8/p3SNrQS8wsIDOXKpPjKX+YqEkY3xVJRs8v3V6Cme6jaFSbtxo4wFeflqEtAdRofwDRBHeVAz3BjQvesveAuNiipLGB+cQNCu05Y6pkuW+wPfLYiX7p8MgpHdoDWJHV9YrqkGZa8d3aSrpa7C4hrqwhDyxhQxl1Nni/sF8DiwHP6iw9bL7x526SLQyAFfILP7sIe8E3AnUT90x+56d1Gexa6bBBBlinVKm98sXmYJlaOzjpngD7LZNriX1QDsKvXjtFx74GrqLUmC4q+hxVBFrNmLnsxFVByVI9FMXq6KQjoJbRCG1/NtVV0Lj+DPUvO/i5QWV83jtNjecAqh4zXpWT7hDyFQ3I62JeSlWKn6AdMYY+pGKKL1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
