travis:
  secure:
    BINSTAR_TOKEN: aP6bOTbDgthCZUZWVytsCHeS3b6bEFzj9WWi7kvuTuLFERPZkz1lfffR3pdutH39tmLT1RluF/2q6ct/zdoxo2QWQJ985tapVwbkbyJSzKt1HYl0icAJg87jHJmlIxxvp+ykuojgG3OF4IU+FwqhOptIX/dTkhCFT4sL0LZf+hiTbT2UQbRD8Zd684Kry0ZiHmHaNxDH5qRz7QKSb5MCi8+mZ/qaapSFEzm6jG5mNZzy7vo7IrJ6FDbUOOXnG0S8IzHYpM5naf3mYMsw7wpGFUS8+v5C480sf9lmN5tL78vfwMu1L+aQpeRVqvDZrc+J4+k4ydRr0Uz2IMbjOXTiChAPZBVUu467PCp7REWdSIFfSkLnmvkjGxXskGZ9MZCgKPNn8LnVjBOLIbg2xGVihzzjxM8WCDajGbyTloIduYo580v1RISpSJPmgWvvdKnQcqBQTUvaJHd6j4bltzo/Dphd2nfB9ARKLN+o9PGjRAZYTVNQDEOphhn8uoXpyZEizfauJWEea72NBdQWGltvxr/rF4vcm8YNG2x9NKi5UnOxZGJe/FiQKn5HccVnccn50lHtQD5+TbxCK4ZIiVS/otLUAzXiq+6zoxu6agUZpvVKtwxNgSBMPWuM7E3gxvykHMwOMemjiEU/uoiw2SsXhCreILpBCp423Tii5Kj99FA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
